# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Decypher' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'Parse', '~> 1.13.0'
    
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    
    # Pods for Decypher
    target 'DecypherTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
