# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'casarao' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Parse'
  pod 'Alamofire', '~> 3.4'
  pod 'ObjectMapper', '~> 1.3'
  pod 'AlamofireObjectMapper', '~> 3.0'

  # Pods for casarao
  target 'casaraoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'casaraoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
